---
- name: Configure Apache2 service
  hosts: all
  tasks:
    - name: Install Apache2 package
      become: yes
      apt:
        name: apache2
        state: present


    - name: Ensure Apache2 is started
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
