---
- name: Install Apache on all hosts
  hosts: all
  become: yes  # Use privilege escalation (sudo) to install packages
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install Apache2 package
      apt:
        name: apache2
        state: present

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes  # Ensure Apache starts on boot

    - name: Check Apache2 status
      command: systemctl status apache2
      register: apache_status
      ignore_errors: yes

    - name: Show Apache2 status
      debug:
        var: apache_status.stdout
