---
- name: Create temp.txt file
  hosts: all
  tasks:
    - name: List files in the current directory
      shell: ls -l
      register: files_list

    - name: Show the listed files
      debug:
        var: files_list.stdout
    # - name: Ensure temp.txt file is created
    #   file:
    #     path: /home/jatin/awx/temp.txt
    #     state: touch
    #     mode: '0644'

# ---
# - name: Configure Apache2 service
#   hosts: all
#   tasks:
#     - name: Install Apache2 package
#       become: true
#       apt:
#         name: apache2
#         state: present


#     - name: Ensure Apache2 is started
#       ansible.builtin.service:
#         name: apache2
#         state: started
#         enabled: true
