- name: Clone a public Git repository
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure destination directory exists
      file:
        path: /home/jatin/awx-POC/demo-pull
        state: directory
        mode: '0755'
      become: true

    - name: Clone the Git repository (Public Repo)
      git:
        repo: "https://github.com/jatinsuthartalentica/ansible-tower-poc.git"
        dest: "/home/jatin/awx-POC/demo-pull"
        version: main  # Change branch if needed
      register: git_clone_result
      become: true

    - name: Debug Git Clone Output
      debug:
        var: git_clone_result
