- name: Clone or Pull Repository from AWX Project
  hosts: all
  gather_facts: no
  tasks:
    - name: Install Git (if not installed)
      package:
        name: git
        state: present
    - name: Enable Github Global SSH Key
      debug:
        var: secure_key
    - name: Ensure the destination directory exists
      file:
        path: "/tmp/demo-pull"
        state: directory
        owner: "jatin"
        group: "jatin"
        mode: '0755'

    - name: Clone the repository if not already cloned
      git:
        repo: "git@github.com:jatinsuthartalentica/ansible-tower-poc.git"
        key_file: "{{ secure_key }}"
        dest: "/tmp/demo-pull"
        clone: yes
        update: yes
      register: git_clone

    - name: Pull the latest changes if already cloned
      git:
        repo: "git@github.com:jatinsuthartalentica/ansible-tower-poc.git"
        key_file: "{{ secure_key }}"
        dest: "/tmp/demo-pull"
        update: yes
      when: git_clone is not changed
