apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: nodejs
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001  # Exposed port (must be between 30000-32767)
  selector:
    app: nodejs
