- name: Clone a Git repository using a role
  hosts: all
  become: true
  tasks:
    - include_role:
        name: git_pull


- name: build docekr image
  hosts: all
  tasks:
    - include_role:
        name: build-docker-image

- name: create namespaces
  hosts: all
  tasks:
    - include_role:
        name: create-namespaces

- name: Create mysql server
  hosts: all
  tasks:
    - include_role:
        name: deploy-mysql

- name: deploy node application
  hosts: all
  tasks:
    - include_role:
        name: deploy-app
