- hosts: all
  tasks:
    - include_role:
        name: pull-code

- hosts: all
  tasks:
    - include_role:
        name: build-docker-image

- hosts: all
  tasks:
    - include_role:
        name: create-namespaces

- hosts: all
  tasks:
    - include_role:
        name: deploy-mysql

- hosts: all
  tasks:
    - include_role:
        name: deploy-app
